Simplify config with plugin defaults
Digitalroot/MediaWiki_PHPBB_Auth pull request #51
Opened 2022-01-30 02:18 UTC by cpeel

Rather than require users to explicitly set all configuration values, encode the default values in the plugin and allow the array in `LocalSettings.php` to override them. This ensures that all values are defined to known-good and reasonable defaults.

This is entirely backwards-compatible and the defaults in the plugin were taken from the `README.md`.

This also reformats the configuration array in `README.md` to be easier to read (see the [rendered version in GitHub](https://github.com/cpeel/MediaWiki_PHPBB_Auth/tree/revamp-readme#mediawiki_phpbb_auth)) and groups related settings together in a logical way.

2022-01-30 02:19 UTC, cpeel commented
FWIW, this is the last set of changes that I intend to make to `MediaWiki_PHPBB_Auth` for the 4.0 release unless users have issues.

2022-01-30 04:34 UTC, JWPlatt requested changes
Nice work!  Much appreciated.  A few comments:

Instructions on how to use multiple wikiGroupName entries has been dropped and should be included.

Database identification comments have been dropped.  Although obvious, clarity for beginners should be maintained, perhaps with minor elaboration so it doesn't appear as redundant as it did..

URLToPHPBB is missing.  Maybe this was only for the login message, but may have been used for subdomain support - not sure.

Typo above UseWikiProfile: "in incompatible".

Login message should retain its more helpful registration link.

2022-01-30 04:55 UTC, cpeel commented
> Instructions on how to use multiple wikiGroupName entries has been dropped and should be included.

I can add more clarity. By making it an array I had hoped it would be obvious that it could take more than one value.

> Database identification comments have been dropped. Although obvious, clarity for beginners should be maintained, perhaps with minor elaboration so it doesn't appear as redundant as it did..

With respect, I don't think there's a lot of value in this:
```
  $wgAuth_Config['MySQL_Port'] = '';  // phpBB MySQL Port number.
```
I'll update the comment above the block to be clearer about when this would be used and where the values would come from.

> URLToPHPBB is missing. Maybe this was only for the login message, but may have been used for subdomain support - not sure.

Yes, it's only used in the login message (see below) and so was removed.

> Login message should retain its more helpful registration link.

The links won't work. PluggableAuth does not output links and shows them as raw HTML. Bold works, but links don't (see [line 101](https://github.com/Digitalroot-Technologies/MediaWiki_PHPBB_Auth/pull/51/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R101)). There is no way around this that I can figure out.

> Typo above UseWikiProfile: "in incompatible".

Thanks for catching that!

2022-01-30 05:21 UTC, Digitalroot commented
Another update before merge?

2022-01-30 05:21 UTC, Digitalroot commented
I like the changes to the ReadMe.

2022-01-30 05:21 UTC, cpeel commented
Yes, I want to address some of @JWPlatt's concerns. Probably tomorrow!

2022-01-30 05:41 UTC, JWPlatt commented
> With respect, I don't think there's a lot of value in this:
> 
>   $wgAuth_Config['MySQL_Port'] = '';  // phpBB MySQL Port number.

It clarifies phpBB vs wiki database and spells things out just a little more.  It does seem obvious/redundant - something to which another word or two could add value.  As mentioned, clarity for beginners.  Obvious?  Yes, to you and me.  Same for wikiGroupName array.

2022-01-30 15:08 UTC, cpeel commented
I've updated the groups and the external database comments to (hopefully) be clearer and more precise.

2022-01-30 15:31 UTC, cpeel commented
Ah! I figured out how to make links work in error message: it's wikiformat. Seems obvious in hindsight. `README.md` updated.

2022-01-30 15:59 UTC, JWPlatt commented
Thanks for the persistence.  :)

2022-02-01 21:43 UTC, Digitalroot approved these changes
Is this ready for a 4.0 release?

2022-02-01 21:43 UTC, merged

2022-02-01 21:47 UTC, cpeel commented
> Is this ready for a 4.0 release?

It's as ready as I know how to make it pending feedback from others. I offered a suggestion on the 4.0 release notes over in this discussion FWIW: https://github.com/Digitalroot-Technologies/MediaWiki_PHPBB_Auth/discussions/48#discussioncomment-2076542

2022-02-01 21:50 UTC, Digitalroot commented
> > Is this ready for a 4.0 release?
> 
> It's as ready as I know how to make it pending feedback from others. I offered a suggestion on the 4.0 release notes over in this discussion FWIW: [#48 (comment)](https://github.com/Digitalroot-Technologies/MediaWiki_PHPBB_Auth/discussions/48#discussioncomment-2076542)

https://github.com/Digitalroot-Technologies/MediaWiki_PHPBB_Auth/releases/tag/untagged-d95a8ba3a4cf80c08eea

2022-02-01 21:54 UTC, Digitalroot commented
I'll let this bake as RC1 and I set a 4.0.0 Release date of 2/28/22 for the initial release.